services:
  telepathy-db:
    image: postgres
    restart: always
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rawr
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$${POSTGRES_USER}", "-d", "$${POSTGRES_DB}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
  telepathy:
    build: .
    restart: on-failure:10
    ports:
      - 24021:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rawr
    depends_on:
      telepathy-db:
        condition: service_healthy

    